CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/cascader/style/index.less, components/icon/icons.tsx, components/list/__tests__/__snapshots__/demo.test.js.snap, components/list/index.en-US.md, components/list/index.tsx, components/list/index.zh-CN.md, components/select/style/index.less, components/style/core/iconfont.less, components/table/Table.tsx, components/table/__tests__/__snapshots__/demo.test.js.snap, components/table/demo/edit-cell.md, components/table/index.en-US.md, components/table/index.zh-CN.md, components/table/interface.tsx, package.json
=> upgrade 0.3.10

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/input/Input.tsx, components/rc-components/select/Select.jsx, components/select/style/index.less, package.json
=> [IMP] upgrade to 0.4.0

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Field.tsx, components-pro/data-set/Record.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md
`DataSet.Field`新增`requestTransform`和`responseTransform`输入属性，用于在发送（或接收）数据之前进行预处理
=> [ADD] DataSet.Field requestTransform & responseTransform prop

components-pro/data-set/DataSet.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
全局配置方法添加分页参数转换参数.
使用方法：
```js
import { configure } from 'choerodon-ui';
configure({
generatePageQuery: pageParams => ({
page: pageParams.page - 1,
size: pageParams.pageSize,
}),
});
```
=> [ADD] Add global configuration generatePageQuery.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/modal-container/ModalContainer.tsx
使用scrollHeight - clientHeight判断滚动条状态
=> [FIX] 页面无滚动条时，弹出默认Modal影响布局

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/text-field/style/mixin.less
=> [FIX] <pro> TextField(and child classes) display style when using addons

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/ColumnFilter.tsx
=> [IMP] <pro>Table/ColumnFilter style

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/text-field/style/mixin.less
修复了字段值为多值时，上浮标签被隐藏input元素遮挡的问题
=> [FIX] <pro> FormField label style with multiple values

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/validator/Validator.tsx
=> [UPD] Cancel the cache strategy in Validator.checkValidity method.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/modal/Modal.tsx, components-pro/modal/demo/footer.md, components-pro/modal/index.en-US.md, components-pro/modal/index.zh-CN.md
footer支持函数类型，参数为内置的ok和cancel按钮，如图
---
=> [IMP] <pro> Modal footer property supports function type.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/KeyValueBar.tsx, components-pro/table/Table.tsx, components-pro/table/TableAdvancedQueryBar.tsx, components-pro/table/TableContext.tsx, components-pro/table/TableToolBar.tsx, components-pro/table/demo/advanced-bar.md, components-pro/table/enum.tsx, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/table/style/index.less, components-pro/table/utils.tsx
向Table组件添加了advancedBar类型的高级搜索特性，如图：
---
=> [ADD] <pro> Table queryBar property supports advancedBar

components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/zh_CN.tsx, components-pro/table/KeyValueBar.tsx, components-pro/table/TableAdvancedQueryBar.tsx
=> [IMP] <pro> Table advanced field: query after field change

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/zh_CN.tsx, components-pro/select/Select.tsx
=> [IMP] <pro> Select shows 'No Match' when searchable and no matching results

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/select/Select.tsx, components-pro/select/demo/filter.md, components-pro/select/demo/optionRenderer.md, components-pro/select/index.en-US.md, components-pro/select/index.zh-CN.md
Select组件添加`optionRenderer`输入属性，提供demo
=> [ADD] <pro> Select optionRenderer input property

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/modal/Sidebar.tsx, components/modal/demo/sidebar.md, components/modal/style/sidebar.less
=> [FIX] width property doesn't work in SideBar

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/modal/style/index.less
=> [IMP] <pro> adjust footer position to viewport bottom in drawer modal

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/form/style/index.less, components/style/themes/default.less
输入框将验证信息纳入组件，整体`margin-bottom: 20px;`
=> [IMP] <pro> Update FormField style under float label layout.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/check-box/CheckBox.tsx, components-pro/check-box/demo/dataset.md, components-pro/field/FormField.tsx, components-pro/radio/Radio.tsx
当`Radio`和`CheckBox`没有包裹`children`时，使用`label`代替`children`
=> [IMP] <pro> Radio, CheckBox use label as children when there's no children

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/ja_JP.tsx, components-pro/locale-context/locale.tsx, components-pro/locale-context/zh_CN.tsx, components-pro/pagination/Pagination.tsx, components-pro/pagination/demo/basic.md, components-pro/pagination/demo/hzero.md, components-pro/pagination/index.zh-CN.md, components-pro/pagination/style/index.less, components-pro/table/demo/basic.md
=> [ADD] <pro>Pagination: Added showQuickJumper property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/spin/demo/dataset.md, components-pro/spin/index.en-US.md, components-pro/spin/index.zh-CN.md, components-pro/table/Table.tsx, components-pro/table/demo/spin.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md
[ADD]<Pro>Spin: Add dataSet binding demo.
[IMP] <Pro>Table: Expand configuration, add related demo.
=> Spin demo.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/core/ViewComponent.tsx, components-pro/form/demo/dataset.md
<pro>Form`: Fix the problem that the form control values are not cleared when clearing the dataset.
=> <pro>Form: Fix the problem that the form control values are not cleared when clearing the dataset.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/Column.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableHeaderCell.tsx
[FIX] <pro>Table: Optimize the performance of autoMaxWidth.
=> [FIX] <pro>Table: Optimize the performance of autoMaxWidth.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/DataSet.tsx, components-pro/data-set/Record.tsx
[FIX] <pro>DataSet.Record: Fix the problem that the `getCascadeRecords` method may have an endless loop.
=> [FIX] <pro>DataSet.Record: Fix the problem that the `getCascadeRecords` method may have an endless loop.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx, components-pro/table/demo/tree.md
<pro>Table: Optimize the performance of tree expand and collapse.
=> [FIX] <pro>Table: Optimize the performance of tree expand and collapse.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/date-picker/DatePicker.tsx, components-pro/field/FormField.tsx, components-pro/tooltip/Tooltip.tsx, components-pro/tooltip/style/index.less, components-pro/trigger/Popup.tsx, components-pro/trigger/Trigger.tsx, components/align/Align.tsx
<pro>Trigger: Optimize the performance.
=> <pro>Trigger: Optimize the performance.

components-pro/core/ViewComponent.tsx, components-pro/data-set/Record.tsx, components-pro/performance-table/Table.tsx, components-pro/table/TableHeader.tsx, components-pro/table/TableRow.tsx, components/icon/Icon.tsx, components/icon/utils.ts, components/rc-components/tree/MotionTreeNode.tsx, components/rc-components/tree/NodeList.tsx, components/rc-components/tree/Tree.tsx, components/rc-components/tree/TreeNode.tsx, components/rc-components/tree/contextTypes.ts, components/rc-components/tree/interface.tsx, components/rc-components/tree/util.tsx, components/rc-components/tree/utils/conductUtil.ts, components/rc-components/tree/utils/treeUtil.ts, components/tree/DirectoryTree.tsx, components/tree/index.tsx, components/tree/utils/dictUtil.ts, typings/custom-typings.d.ts
=> [FIX] Fixed typescript error

components-pro/data-set/Record.tsx
[FIX] <pro>DataSet.Record: Fixed the reset method problem of Record.
=> [FIX] <pro>DataSet.Record: Fixed the reset method problem of Record.

.eslintignore, .gitignore, components-pro/tree-select/TreeSelect.tsx, components-pro/tree-select/style/index.less, components-pro/tree/util.tsx, components/rc-components/tree/Tree.tsx, components/tree/index.tsx
[ADD] <pro>TreeSelect: Added keyboard operation.
=> [ADD] <pro>TreeSelect: Added keyboard operation.

components-pro/table/TableHeader.tsx
[FIX] <pro>Table: Fixed border style of header issue.
=> [FIX] <pro>Table: Fixed border style of header issue.

components-pro/table/TableBody.tsx, components-pro/table/TableEditor.tsx, components-pro/table/style/index.less
[FIX] <pro>Table: Fixed Table editor zIndex error.
=> [FIX] <pro>Table: Fixed Table editor zIndex error.

components-pro/table/TableStore.tsx, components-pro/table/customization-settings/column-groups/ItemSuffix.tsx
[FIX] <pro>Table: Fixed customization cannot effect the column with key ant without name property.
=> [FIX] <pro>Table: Fixed customization cannot effect the column with key ant without name property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableCell.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableStore.tsx, components/configure/index.tsx
[ADD] configure: Added tableColumnTooltip property.
[FIX] <pro>Table: When customizable is false, column merging is prohibited.
=> [FIX] <pro>Table: When customizable is false, column merging is prohibited. [ADD] configure: Added tableColumnTooltip property.

components-pro/table/Table.tsx, components-pro/table/style/index.less
[FIX] <pro>Table: Fix border issue.
=> [FIX] <pro>Table: Fix border issue.

components-pro/table/TableEditor.tsx
[FIX] <pro>Table: Fix the problem of editor's position in virtual mode.
=> [FIX] <pro>Table: Fix the problem of editor's position in virtual mode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableCell.tsx, components-pro/table/TableEditor.tsx
[FIX] <pro>Table: Fixed the problem that editor will not auto scroll into view in virtual mode.
=> [FIX] <pro>Table: Fixed the problem that editor will not auto scroll into view in virtual mode.

components-pro/table/Table.tsx, components-pro/table/TableEditor.tsx, components-pro/table/TableRow.tsx, package-lock.json, site/theme/template/Layout/index.jsx
[FIX] <pro>Table: Fixed the problem of editor.
=> [FIX] <pro>Table: Fixed the problem of editor.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/lov/Lov.tsx, components-pro/lov/demo/dataset.md, components-pro/select/Select.tsx
[IMP] <pro>Lov: Prompt the priority of searchable attribute when value is false.
=> [IMP] <pro>Lov: Prompt the priority of searchable attribute when value is false.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Field.tsx
[FIX] <pro>DataSet.Field: Fix the problem that dynamicProps may report errors.
=> [FIX] <pro>DataSet.Field: Fix the problem that dynamicProps may report errors.  

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableCell.tsx, components-pro/table/TableEditor.tsx, components-pro/table/TableRow.tsx, components-pro/table/style/index.less
[IMP] <pro>Table: Optimize the performance of editors.
=> [IMP] <pro>Table: Optimize the performance of editors.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/core/ViewComponent.tsx, components-pro/output/Output.tsx, components-pro/table/Table.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableEditor.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components-pro/table/VirtualWrapper.tsx
[IMP] <pro>Table: Optimize virtual scrolling performance.
=> [IMP] <pro>Table: Optimize virtual scrolling performance.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/lov/LovView.tsx, components-pro/table/customization-settings/CustomizationSettings.tsx, components-pro/table/customization-settings/tree/TreeNode.tsx, components-pro/table/demo/customized.md, components-pro/table/style/customization.less, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
[ADD] configure: Added lovTableCustomizable property.
=> [ADD] configure: Added lovTableCustomizable property.

components-pro/data-set/Record.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/modal/Modal.tsx, components-pro/table/Table.tsx, components-pro/table/TableFooter.tsx, components-pro/table/TableHeader.tsx, components-pro/table/TableStore.tsx, components-pro/table/customization-settings/CustomizationSettings.tsx, components-pro/table/style/customization.less
[IMP] <pro>Table: Optimize table customization height setting as WYSIWYG.
=> [IMP] <pro>Table: Optimize table customization height setting as WYSIWYG.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/field/FormField.tsx
[FIX] <pro>FormField: Fix the problem that the value will not be verified when the value is not changed.
=> [FIX] <pro>FormField: Fix the problem that the value will not be verified when the value is not changed.

components-pro/table/Table.tsx
[FIX] <pro>Table: Fixed virtual scrolling error.
=> [FIX] <pro>Table: Fixed virtual scrolling error.

components-pro/text-field/TextField.tsx, components/_util/UnitConvertor.tsx
[FIX] Fixed toPx method of UnitConvertor issue.
=> [FIX] Fixed toPx method of UnitConvertor issue.

components-pro/data-set/utils.tsx, components-pro/table/demo/basic.md
[FIX] <pro>DataSet: Fixed defaultValue of multiple field issue.
=> [FIX] <pro>DataSet: Fixed defaultValue of multiple field issue.

components-pro/data-set/DataSet.tsx, components-pro/table/demo/basic.md
[FIX] <pro>DataSet: Fixed defaultValue issue.
=> [FIX] <pro>DataSet: Fixed defaultValue issue.

components-pro/data-set/Record.tsx
[FIX] <pro>DataSet: Fixed some issues of defaultValue.
=> [FIX] <pro>DataSet: Fixed some issues of defaultValue.

components-pro/data-set/Record.tsx
[FIX] <pro>DataSet.Field: Fixed transformResponse issue.
=> [FIX] <pro>DataSet.Field: Fixed transformResponse issue.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/utils.tsx, components-pro/table/Table.tsx
[FIX] <pro>Table: Fix the problem of constantly shaking.
=> [FIX] <pro>Table: Fix the problem of constantly shaking.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/button/style/index.less, components-pro/overflow-tip/index.tsx, components-pro/table/TableEditor.tsx, components-pro/table/demo/basic.md, components/_util/createChains.tsx, components/rc-components/menu/MenuItem.jsx, components/ripple/RippleChild.tsx, components/ripple/index.tsx
[FIX] <pro>Table: Fix the positioning problem of the editor when the current record of the DataSet changes.
=> [FIX] <pro>Table: Fix the positioning problem of the editor when the current record of the DataSet changes.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/DataSet.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md
[ADD] <pro>DataSet: Added getQueryParameter method and change queryParameter to an observable attribute.
=> [ADD] <pro>DataSet: Added getQueryParameter method and change queryParameter to an observable attribute.

components-pro/data-set/DataSet.tsx
[FIX] <DataSet>: Fixed error in setQueryParameter method.
=> [FIX] <DataSet>: Fixed error in setQueryParameter method.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/option/normalizeOptions.tsx, components-pro/select/Select.tsx, components-pro/select/demo/searchable.md, components-pro/text-field/RenderedText.tsx, components-pro/text-field/TextField.tsx
[FIX] <pro>Select.Option: Fix the rendering problem when children are ReactNode.
=> [FIX] <pro>Select.Option: Fix the rendering problem when children are ReactNode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Field.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/field/FormField.tsx, components-pro/form/demo/basic.md, components-pro/form/demo/dataset.md, components-pro/output/style/index.less, components-pro/radio/style/index.less, components-pro/select-box/SelectBox.tsx, components-pro/table/TableCell.tsx, components-pro/table/demo/basic.md, components-pro/table/style/index.less, components-pro/text-field/RenderedText.tsx, components-pro/text-field/TextField.tsx, components-pro/text-field/style/mixin.less, components/style/themes/default.less
[ADD] <pro> DataSet.Field: Added highlight property.
=> [ADD] <pro> DataSet.Field: Added highlight property.

components-pro/button/Button.tsx, components-pro/button/demo/tooltip.md, components-pro/button/style/index.less
[FIX] <pro>Button: Fixed disabled tooltip style.
=> [FIX] <pro>Button: Fixed disabled tooltip style.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/button/Button.tsx, components-pro/button/style/index.less, components-pro/data-set/Field.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/data-set/utils.tsx, components-pro/field/FormField.tsx, components-pro/field/style/mixin.less, components-pro/form/demo/basic.md, components-pro/form/demo/dataset.md, components-pro/table/style/index.less, components-pro/text-field/style/mixin.less, components-pro/tooltip/Tooltip.tsx, components/style/themes/default.less, components/tooltip/index.tsx
[FIX] <pro>Table: Fix the problem of an infinite loop caused by empty  value of idField in tree paging data.
=> [FIX] <pro>Table: Fix the problem of an infinite loop caused by empty  value of idField in tree paging data.

components-pro/text-field/style/mixin.less
[FIX] <pro>TextField: Fixed required border color issue.
=> [FIX] <pro>TextField: Fixed required border color issue.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/button/style/index.less, components-pro/data-set/Field.tsx, components-pro/date-picker/DatePicker.tsx, components-pro/field/FormField.tsx, components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/ja_JP.tsx, components-pro/locale-context/locale.tsx, components-pro/locale-context/zh_CN.tsx, components-pro/overflow-tip/index.tsx, components-pro/table/style/index.less, components-pro/validator/rules/typeMismatch.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
[ADD] configure: Added showInvalidDate property.
=> [ADD] configure: Added showInvalidDate property.

components-pro/field/style/mixin.less, components-pro/text-field/style/mixin.less, components/style/themes/default.less
[IMP] Added some less variable.
=> [IMP] Added some less variable.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/_util/isFragment.tsx, components-pro/form/Form.tsx, components-pro/form/FormVirtualGroup.tsx, components-pro/form/demo/grid.md, components-pro/form/demo/virtualGroup.md, components-pro/option/normalizeOptions.tsx, components-pro/performance-table/Table.tsx, components-pro/select/demo/basic.md, components-pro/table/TableStore.tsx, components-pro/table/demo/basic.md, components-pro/text-field/style/mixin.less, site/theme/template/Layout/index.jsx
[IMP] &lt;pro&gt;Select.Option: Support ReactFragment nesting.
[FIX] &lt;pro&gt;TextField: Fixed border color of focus status.
=> [IMP] <pro>Select.Option: Support ReactFragment nesting.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/DataSet.tsx, components-pro/data-set/Field.tsx, components-pro/data-set/Record.tsx, components-pro/data-set/utils.tsx, components-pro/field/FormField.tsx, components-pro/output/Output.tsx, components-pro/table/demo/basic.md, components-pro/table/demo/cascade.md
[IMP] <pro>DataSet.Field: Optimize some problems of chain binding.
=> [IMP] <pro>DataSet.Field: Optimize some problems of chain binding.

components-pro/button/style/index.less, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/data-set/utils.tsx, components-pro/dropdown/index.en-US.md, components-pro/dropdown/index.zh-CN.md, components-pro/overflow-tip/index.tsx, components-pro/tooltip/index.en-US.md, components-pro/tooltip/index.zh-CN.md, components/style/themes/default.less
[FIX] <pro>DataSet: Fixed the problem of paging tree data loading logic.
=> [FIX] <pro>DataSet: Fixed the problem of paging tree data loading logic.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/core/ViewComponent.tsx, components-pro/data-set/DataSet.tsx, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
[ADD] configure：Added performanceEnabled, onPerformance properties.
=> [ADD] configure：Added performanceEnabled, onPerformance properties.

components-pro/auto-complete/AutoComplete.tsx, components-pro/select/Select.tsx, components-pro/tree-select/TreeSelect.tsx, components-pro/trigger/Trigger.tsx, components/rc-components/tree/Tree.tsx
[FIX] <pro>TriggerField: Fix blur event will bubble to outside when some focusable element in pop content is focused.
=> [FIX] <pro>TriggerField: Fix blur event will bubble to outside when some focusable element in pop content is focused.

components-pro/data-set/Record.tsx, components-pro/field/style/mixin.less, components-pro/table/style/index.less
[IMP] <pro> Record: Optimize the performance of toData method.
=> [IMP] <pro> Record: Optimize the performance of toData method.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Record.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/data-set/utils.tsx, components-pro/output/style/index.less, components-pro/table/SelectionTips.tsx, components-pro/table/Table.tsx, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components/style/themes/default.less, package.json
[ADD] <pro>DataSet.Record: The get method supports the field name array parameter.
[ADD] <pro>Table: Added showSelectionCachedButton property.
=> [ADD] <pro>DataSet.Record: The get method supports the field name arr… 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/check-box/style/index.less, components-pro/data-set/Record.tsx, components-pro/data-set/utils.tsx, components-pro/field/FormField.tsx, components-pro/field/style/mixin.less, components-pro/output/style/index.less, components-pro/radio/Radio.tsx, components-pro/radio/style/index.less, components-pro/radio/style/mixin.less, components-pro/switch/Switch.tsx, components-pro/trigger/Trigger.tsx, components/style/themes/default.less
[IMP] <pro>Radio: Optimize the label content overflow tooltip.
[IMP] <pro>DataSet.Record: Optimize the getField method.
=> [IMP] <pro>DataSet.Record: Optimize the getField method.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/_util/isEmpty.tsx, components-pro/data-set/Record.tsx, components-pro/field/FormField.tsx, components-pro/output/Output.tsx, components-pro/table/TableCellInner.tsx
[IMP] <pro>Output: Optimize the display of empty values.
=> [IMP] <pro>Output: Optimize the display of empty values.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/modal-container/ModalContainer.tsx, components-pro/modal-manager/index.tsx, components-pro/modal/Modal.tsx, components-pro/modal/demo/across-iframe.md, components-pro/modal/utils.tsx, site/theme/index.js, site/theme/template/Content/ComponentDoc.jsx, site/theme/template/Content/Demo.jsx, site/theme/template/Iframe/index.jsx
[IMP] <pro>Modal: Support traversing iframes in the same domain.
=> [IMP] <pro>Modal: Support traversing iframes in the same domain.

components-pro/date-picker/TimesView.tsx, components-pro/field/FormField.tsx, components-pro/screening/ScreeningItem.tsx, components-pro/trigger/Popup.tsx
[FIX] <pro>FormField: autoFocus has no effect.
=> [FIX] <pro>FormField: autoFocus has no effect.

components-pro/table/TableCellInner.tsx
[FIX] <pro>Table.Column: Fixed validationMessage is not shown.
=> [FIX] <pro>Table.Column: Fixed validationMessage is not shown.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/output/Output.tsx, components-pro/table/Column.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/demo/pristine.md, components/configure/index.tsx
[ADD] configure: Added tableVirtualCell property.
=> [ADD] configure: Added tableVirtualCell property.

components-pro/index.tsx, components-pro/table/StickyShadow.tsx, components-pro/table/Table.tsx, components-pro/table/TableBody.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableFooter.tsx, components-pro/table/TableHeader.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/style/index.less, components-pro/use-computed/index.tsx, components-pro/use-computed/style/index.tsx
[IMP] <pro>Table: Optimize scroll bar performance.
=> [IMP] <pro>Table: Optimize scroll bar performance.

components-pro/button/style/index.less, components-pro/table/TableCol.tsx, components-pro/table/TableFooter.tsx, components-pro/table/TableHeader.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableWrapper.tsx, components-pro/table/demo/column-group.md, components-pro/table/style/index.less, components-pro/text-field/style/mixin.less, components/style/themes/default.less, components/tag/style/index.less, package.json
[IMP] <pro>Table: Optimize the border style.
=> [IMP] <pro>Table: Optimize the border style.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/select-box/SelectBox.tsx, components-pro/table/Column.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableHeader.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/demo/aggregation.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/table/style/index.less, components-pro/text-field/TextField.tsx
[ADD] <pro>Table.Column: Added hiddenInAggregation property.
[IMP] <pro>Table: Optimize the performance of adjusting column width.
[IMP] <pro>SelectBox: Adjust the default value of checkValueOnOptionsChange to false.
[FIX] <pro>FormField: Fix the problem of not rendering when the renderer returns a number.
=> [ADD] <pro>Table.Column: Added hiddenInAggregation property. 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableHeaderCell.tsx
[IMP] <pro>Table: Optimize the performance of adjusting column width.
=> [IMP] <pro>Table: Optimize the logic of adjusting column width.

components-pro/table/TableHeaderCell.tsx
[IMP] <pro>Table: Optimize the animation in adjusting the width of  auto-width column.
=> [IMP] <pro>Table: Optimize the animation in adjusting the width of  auto-width column.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableCell.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableRow.tsx, components-pro/table/demo/aggregation.md
[FIX] <pro>Table: Fix virtualCell not working.
=> [FIX] <pro>Table: Fix virtualCell not working.

components-pro/radio/Radio.tsx, components-pro/table/TableCell.tsx
[FIX] <pro>Table: Fix style of virtualCell.
=> [FIX] <pro>Table: Fix style of virtualCell.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/cascader/Cascader.tsx, components-pro/color-picker/ColorPicker.tsx, components-pro/data-set/DataSet.tsx, components-pro/data-set/Field.tsx, components-pro/data-set/Record.tsx, components-pro/data-set/utils.tsx, components-pro/date-picker/DatePicker.tsx, components-pro/email-field/EmailField.tsx, components-pro/field/FormField.tsx, components-pro/field/utils.tsx, components-pro/number-field/NumberField.tsx, components-pro/radio/Radio.tsx, components-pro/select-box/SelectBox.tsx, components-pro/select/Select.tsx, components-pro/table/Column.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableRow.tsx, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/url-field/UrlField.tsx, components-pro/validator/Validator.tsx
[ADD] Added aggregation parameter to the command hook.
[IMP] <pro>DataSet: Memory optimization.
=> [IMP] <pro>DataSet: Memory optimization.

components-pro/field/FormField.tsx
[FIX] <pro>FormField: Fix issue in validate.
=> [FIX] <pro>FormField: Fix issue in validate.

components-pro/core/ViewComponent.tsx, components-pro/data-set/DataSetComponent.tsx, components-pro/field/FormField.tsx, components-pro/form/Form.tsx
[FIX] <pro>FormField: Fix float label may be not displayed.
=> [FIX] <pro>FormField: Fix float label may be not displayed.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/core/ViewComponent.tsx, components-pro/data-set/Field.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/lov/Lov.tsx, components-pro/lov/LovView.tsx, components-pro/select/Select.tsx, components-pro/stores/LovCodeStore.tsx, components-pro/table/TableWrapper.tsx
[FIX] <pro>Lov: Fix the problem that there is no animation in the pop-up window.
=> [FIX] <pro>Lov: Fix the problem that there is no animation in the pop-up window.

components-pro/data-set/Field.tsx
[FIX] <pro>DataSet.Field: Fix pending status.
=> [FIX] <pro>DataSet.Field: Fix pending status.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Field.tsx, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
[ADD] configure: Added tableVirtual property.
=> [ADD] configure: Added tableVirtual property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/field/FormField.tsx, components-pro/form/FormItemLabel.tsx, components-pro/form/Item.tsx, components-pro/output/MultiLine.tsx, components-pro/table/Table.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableFooter.tsx, components-pro/table/TableFooterCell.tsx, components-pro/table/TableHeader.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableHeaderRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx
[FIX] <pro>Table: Fix the problem that the column tooltip cannot be closed when the cell is destroyed.
=> [FIX] <pro>Table: Fix the problem that the column tooltip cannot be closed when the cell is destroyed.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/code-area/CodeArea.tsx, components-pro/code-area/demo/basic.md, components-pro/code-area/demo/controlled.md, components-pro/code-area/demo/dataset.md, components-pro/code-area/demo/html-format.md, components-pro/code-area/demo/js-format.md, components-pro/code-area/demo/json-format.md, components-pro/code-area/demo/theme.md, components-pro/code-area/demo/yaml-format.md, components-pro/code-area/style/index.less, components-pro/field/FormField.tsx
[FIX] <pro>CodeArea: Fix float label style.
=> [FIX] <pro>CodeArea: Fix float label style.

components-pro/data-set/DataSet.tsx, components-pro/data-set/Record.tsx
[FIX] <pro>DataSet: Revert some computed value.
=> [FIX] <pro>DataSet: Revert some computed value.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Field.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/lov/Lov.tsx, components-pro/lov/LovView.tsx, components-pro/lov/demo/tree.md, components-pro/text-field/TextField.tsx, components-pro/tree-select/TreeSelect.tsx, components/anchor/Anchor.tsx
[ADD] DataSet.Field: Added showCheckedStrategy property.
[FIX] <pro>Lov: Fix the problem that multiple selections cannot be made when the selectionMode property of Table is click.
=> [ADD] DataSet.Field: Added showCheckedStrategy property.

components-pro/field/utils.tsx, components-pro/modal/Modal.tsx, components-pro/output/Output.tsx, components-pro/output/utils.tsx, components-pro/picture/PictureViewer.tsx, components-pro/table/TableCellInner.tsx
[FIX] Fix the circular dependency problem.
=> [FIX] Fix the circular dependency problem.

components-pro/attachment/Attachment.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/style/index.less, components-pro/data-set/AttachmentFile.tsx
[FIX] <pro> Attachment: Fixed some problem.
=> [FIX] <pro> Attachment: Fixed some problem.

components-pro/data-set/DataSet.tsx
[FIX] <pro>DataSet: Fixed typescript error of feedback in DataSetProps.
=> [FIX] <pro>DataSet: Fixed typescript error of feedback in DataSetProps.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/Record.tsx, components-pro/date-picker/DatePicker.tsx, components-pro/date-picker/TimesView.tsx, components-pro/date-picker/demo/range.md, components-pro/date-picker/index.en-US.md, components-pro/date-picker/index.zh-CN.md, components-pro/date-picker/style/index.less, components-pro/field/FormField.tsx, components-pro/field/utils.tsx, components-pro/lov/Lov.tsx, components-pro/lov/LovView.tsx, components-pro/lov/style/index.less, components-pro/select/Select.tsx, components-pro/select/style/mixin.less, components-pro/table/TableCellInner.tsx, components-pro/text-field/TextField.tsx, components-pro/text-field/style/mixin.less, components-pro/validator/rules/valueMissing.tsx, package-lock.json
[ADD] <pro>DatePicker: Added editorInPopup, defaultTime properties. 
[FIX] <pro>TimePicker: Fix the display problem of the minute and second selection box in the 12-hour format.
=> [ADD] <pro>DatePicker: Added editorInPopup, defaultTime properties. 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/style/index.less, components-pro/auto-complete/AutoComplete.tsx, components-pro/date-picker/DatePicker.tsx, components-pro/date-picker/demo/range.md, components-pro/date-picker/index.en-US.md, components-pro/date-picker/index.zh-CN.md, components-pro/lov/LovView.tsx, components-pro/picture/Picture.tsx, components-pro/select/Select.tsx, components-pro/text-area/TextArea.tsx, components-pro/text-field/RenderedText.tsx, components-pro/text-field/TextField.tsx, components-pro/text-field/style/mixin.less
[IMP] <pro>Attachment: Optimize dnd, preview and label display. 
[FIX] <pro>DatePicker: Fix display problems in isFlat and range mode.
=> [IMP] <pro>Attachment: Optimize dnd, preview and label display. 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/DataSet.tsx, components-pro/data-set/Record.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/date-picker/demo/range.md, components-pro/lov/LovView.tsx, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx, components-pro/table/demo/advanced-bar.md, components-pro/table/demo/column-group.md, components-pro/table/demo/filterbar.md, components-pro/table/demo/tree-async-paging.md, components-pro/table/demo/tree-async.md, components-pro/table/demo/tree-performance.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/text-field/index.en-US.md, components-pro/text-field/index.zh-CN.md, components-pro/tree-select/TreeSelect.tsx, components-pro/tree-select/demo/async.md, components-pro/tree/demo/async.md, components-pro/tree/index.tsx
[ADD] <pro>DataSet: Added childrenField properties.
=> [ADD] <pro>DataSet: Added childrenField properties.

components-pro/_util/treeUtils.tsx, components-pro/attachment/Attachment.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/demo/dataset.md, components-pro/attachment/style/index.less, components-pro/data-set/DataSet.tsx, components-pro/data-set/Record.tsx, components-pro/data-set/utils.tsx, components-pro/field/FormField.tsx, components-pro/lov/Lov.tsx, components-pro/lov/demo/dataset.md, components-pro/table/demo/tree-performance.md, components-pro/table/demo/tree.md, components-pro/text-field/TextField.tsx
[FIX] <pro>DataSet: Fix some problem of childrenField.
=> [FIX] <pro>DataSet: Fix some problem of childrenField.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/utils.tsx, components-pro/lov/demo/dataset.md, components-pro/table/demo/tree-performance.md, components-pro/table/demo/tree.md, components/tabs/TabBar.tsx
[FIX] Tabs: Fix the problem of possible misalignment of ink bar.
=> [FIX] Tabs: Fix the problem of possible misalignment of ink bar.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableCellInner.tsx
[IMP] <pro>Table: Optimized that cells without editor can also display small triangles.
=> [IMP] <pro>Table: Optimized that cells without editor can also display small triangles.

components-pro/date-picker/DatePicker.tsx, components-pro/field/FormField.tsx, components-pro/trigger-field/TriggerField.tsx
[FIX] <pro>DatePicker: Fixed some problem in editorInPopup mode.
=> [FIX] <pro>DatePicker: Fixed some problem in editorInPopup mode.

components-pro/table/TableHeaderCell.tsx, components-pro/table/TableRow.tsx, components-pro/text-field/TextField.tsx
[FIX] <pro>DatePicker: Fixed placeholder not display in float label and range mode.
[FIX] <pro>Table: Fixed virtualCell maybe not displayed.
=> [FIX] <pro>DatePicker: Fixed placeholder not display in float label and range mode.

components-pro/text-field/TextField.tsx
[FIX] <pro>DatePicker: Fixed placeholder display problem in float label
=> [FIX] <pro>DatePicker: Fixed placeholder display problem in float label

components-pro/table/TableCell.tsx, components-pro/table/TableRow.tsx
[FIX] <pro>Table: Fixed virtualCell maybe not displayed.
=> [FIX] <pro>Table: Fixed virtualCell maybe not displayed.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/_util/measureTextWidth.tsx, components-pro/lov/Lov.tsx, components-pro/overflow-tip/index.tsx, components-pro/overflow-tip/util.tsx, components-pro/select/Select.tsx
[FIX] <pro>Button: Fix the problem that Tooltip will be displayed even if the content is overflow when the tooltip is overflow. 
[FIX] <pro>Select: Fix placeholder is also diplayed in multiple mode if value is not empty. 
[FIX] <pro>Lov: Fix the problem that the onClick property of button mode has no effect.
=> [FIX] <pro>Lov: Fix the problem that the onClick property of button mode has no effect.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/trigger/enum.tsx, components/configure/index.en-US.md, components/configure/index.zh-CN.md, components/style/color/colors.less, components/tag/demo/colorful.md, components/tag/index.tsx, components/tag/style/index.less
=> [ADD] Tag: Added gray color.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/locale-context/zh_CN.tsx, components-pro/number-field/NumberField.tsx, components-pro/pagination/Pagination.tsx, components-pro/pagination/demo/basic.md, components-pro/pagination/demo/showQuickJumper.md, components-pro/pagination/style/index.less, components-pro/table/TableCellInner.tsx, components/tabs/TabContent.tsx, components/tabs/Tabs.tsx, components/tabs/TabsContext.tsx, components/tabs/TabsWithContext.tsx, components/tabs/utils.tsx
[IMP] <pro>Pagination: Optimize the display of quick jumper.
=> [IMP] <pro>Pagination: Optimize the display of quick jumper.

components-pro/attachment/demo/dataset.md, components-pro/field/FormField.tsx, components-pro/radio/Radio.tsx, components-pro/table/demo/basic.md, components-pro/table/style/index.less, components-pro/text-field/TextField.tsx
[FIX] <pro>Attachment: Fix the error when label is ReactElement.
[FIX] <pro>Table: Fixed pagination style.
=> [FIX] <pro>Attachment: Fix the error when label is ReactElement.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/DataSet.tsx, components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/ja_JP.tsx, components-pro/locale-context/zh_CN.tsx, components-pro/pagination/Pagination.tsx, components-pro/pagination/QuickJumper.tsx, components-pro/pagination/style/index.less, components/tabs/TabBar.tsx, components/tabs/Tabs.tsx, components/tabs/TabsContext.tsx, components/tabs/TabsWithContext.tsx, components/tabs/index.en-US.md, components/tabs/index.zh-CN.md
[ADD] Tabs: Added hideOnlyGroup property.
[IMP] <pro>Pagination: Optimize the display of quick jumper.
=> [ADD] Tabs: Added hideOnlyGroup property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentList.tsx, components-pro/attachment/demo/dataset.md, components-pro/attachment/demo/popup.md, components-pro/data-set/Field.tsx, components-pro/date-picker/demo/range.md, components-pro/field/FormField.tsx, components-pro/field/utils.tsx, components-pro/select/Select.tsx, components-pro/table/TableCellInner.tsx, components/align/domAlign.tsx, components/tabs/Tabs.tsx, components/tabs/style/index.less, site/theme/static/demo.less, site/theme/template/Content/Demo.jsx
[FIX] <pro>Attachment: Fix the problem that the quantity is not displayed.
[FIX] <pro>DatePicker: Fix the problem of setting when the range is object and multiple.
=> [FIX] <pro>Attachment: Fix the problem that the quantity is not displayed.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/form/demo/float-label.md, components-pro/form/demo/layout.md, components-pro/table/TableCellInner.tsx, components-pro/table/demo/basic.md, components-pro/text-area/TextArea.tsx, components-pro/text-area/style/index.less
[FIX] <pro>TextArea: Fix the style problem when dragging the width.
[FIX] <pro>Table: Fix the display problem when the editor is SelectBox in multiple mode.
=> [FIX] <pro>TextArea: Fix the style problem when dragging the width.

components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components/alert/style/index.less, components/style/themes/default.less
[ADD] Alert: Added less variables.
=> [ADD] Alert: Added less variables.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentList.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/demo/basic.md, components-pro/attachment/style/index.less, components-pro/data-set/AttachmentFile.tsx, components-pro/data-set/Field.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components/alert/style/index.less, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md, components/trigger/TriggerChild.tsx, site/theme/mock/attachment.js
[IMP] <pro>Attachment: Optimize the display of deleting.
=> [IMP] <pro>Attachment: Optimize the display of deleting.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/Table.tsx, components-pro/table/demo/basic.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components/tabs/style/index.less
[ADD] <pro>Table: deprecate autoMaxWidth property.
=> [ADD] <pro>Table: deprecate autoMaxWidth property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/style/index.less, components/tabs/Count.tsx, components/tabs/demo/group.md
[FIX] <pro>Attachment: Fixed the title style with preview link.
[IMP] Tabs: Optimized to not display when count is zero.
=> [FIX] <pro>Attachment: Fixed the title style with preview link.

components-pro/data-set/Field.tsx
[FIX] <pro>Attachment: Fix the problem that the attachment list are not displayed in popup and dataset mode.
=> [FIX] <pro>Attachment: Fix the problem that the attachment list are not displayed in popup and dataset mode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/date-picker/DatePicker.tsx, components-pro/date-picker/demo/dataset.md, components-pro/lov/Lov.tsx, components-pro/lov/demo/dataset.md
[FIX] <pro>DatePicker: Fix the problem that spaces cannot be entered.
[FIX] <pro>DatePicker: Fix the problem that the defaultTime does not work when entering a value.
[FIX] <pro>Lov: Fix the problem that the drop-down box cannot pop up after closing the Modal in searchFieldInPopup mode.
=> [FIX] <pro>DatePicker: Fix the problem that spaces cannot be entered.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentGroup.tsx, components-pro/attachment/demo/group.md, components-pro/attachment/demo/table.md, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md, components-pro/attachment/style/index.less, components-pro/button/index.en-US.md, components-pro/button/index.zh-CN.md
[ADD] <pro>Attachment.Group: Added Attachment.Group component.
=> [ADD] <pro>Attachment.Group: Added Attachment.Group component.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/DataSet.tsx, components-pro/data-set/utils.tsx, components-pro/lov/Lov.tsx, components-pro/tree/util.tsx, components/tabs/style/index.less
[FIX]<pro>DataSet: Fix the problem of incorrect field sequence after adding new fields.
=> [FIX] <pro>DataSet: Fix the problem of incorrect field sequence after… 

components-pro/performance-table/Table.tsx
=> [FIX] <pro>PerformanceTable: Fix the some problem of table and support async after dragging. 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx
[FIX] <pro>Attachment: Fix the problem that the children and className properties has no effect.
=> [FIX] <pro>Attachment: Fix the problem that the children and className properties has no effect.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/configure/index.tsx, components-dataset/data-set/DataSet.tsx, components-dataset/data-set/Record.tsx, components-dataset/data-set/utils.tsx, components-dataset/index.ts, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/form/Form.tsx, components-pro/form/demo/disabled.md, components-pro/modal-container/ModalContainer.tsx, components-pro/table/demo/basic.md, components-pro/table/demo/tree-async.md, components-pro/table/utils.tsx, components/configure/index.tsx, components/rc-components/table/Table.jsx
[ADD] <pro>DataSet: Added record property.
=> [ADD] <pro>DataSet: Added record property.

components-pro/lov/Lov.tsx, components-pro/lov/LovView.tsx
[FIX]<pro>Lov: Fix the selected fail when single option
=> [FIX]<pro>Lov: Fix the selected fail when single option

components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentGroup.tsx, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md
[ADD] <pro>Attachment.Group: Added text property.
=> [ADD] <pro>Attachment.Group: Added text property.

components-pro/attachment/AttachmentGroup.tsx, components-pro/attachment/demo/group.md, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md
[ADD] <pro>Attachment.Group: Added count property.
=> [ADD] <pro>Attachment.Group: Added count property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/configure/index.tsx, components-dataset/data-set/Field.tsx, components-dataset/stores/AttachmentStore.tsx, components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentList.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md, components/configure/index.en-US.md, components/configure/index.zh-CN.md
[ADD] <pro>Attachment: Added isPublic property.
=> [ADD] <pro>Attachment: Added isPublic property.

components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentGroup.tsx
[ADD] <pro>Attachment.Group: Added empty render.
=> [ADD] <pro>Attachment.Group: Added empty render.

components-pro/attachment/Item.tsx
[FIX] <pro>Attachment: Fix picture preview in public mode.
=> [FIX] <pro>Attachment: Fix picture preview in public mode.

components-pro/attachment/Item.tsx
[FIX] <pro>Attachment: Fix preview logic.
=> [FIX] <pro>Attachment: Fix preview logic.

components-pro/modal-container/ModalContainer.tsx, components-pro/modal/Modal.tsx, components-pro/modal/demo/customizedMask.md
[FIX] <pro>Modal: Fix the unmasked modal box problem.
=> [FIX] <pro>Modal: Fix the unmasked modal box problem.

components-pro/modal/Modal.tsx
[FIX] <pro>Modal: Fix shouldComponentUpdate problem.
=> [FIX] <pro>Modal: Fix shouldComponentUpdate problem.

components-pro/modal-container/ModalContainer.tsx, components-pro/modal/Modal.tsx, components-shared/modal-manager/index.tsx
[FIX] <pro>Modal: Fix some problem in embeded mode.
=> [FIX] <pro>Modal: Fix some problem in embeded mode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/Field.tsx, components-dataset/data-set/utils.tsx, components-dataset/interface.ts, components-dataset/stores/LovCodeStore.tsx, components-pro/lov/demo/dataset.md
[ADD] <pro>DataSet.Field: optionsProps property supports hooks.
=> [ADD] <pro>DataSet.Field: optionsProps property supports hooks.

components-pro/table/Column.tsx
[FIX] <pro>Table: Fix horizontal scrolling problem caused by tableColumnDefaultWidth.
=> [FIX] <pro>Table: Fix horizontal scrolling problem caused by tableCol… 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/form/demo/label-layout.md, components-pro/table/Table.tsx
[FIX] <pro>Table: Fix the height problem that may be caused when switching the display.
=> [FIX] <pro>Table: Fix the height problem that may be caused when switching the display.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/Column.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableStore.tsx, components-pro/table/demo/aggregation.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md
[ADD] <pro>Table.Column: Added aggregationLimitDefaultExpanded property.
=> [ADD] <pro>Table.Column: Added aggregationLimitDefaultExpanded property.

components-pro/table/style/index.less, components-pro/text-field/TextField.tsx, components-pro/text-field/style/mixin.less
[IMP] <pro>TextField: Optimize multiple style.
=> [IMP] <pro>TextField: Optimize multiple style.

components-pro/table/Table.tsx
[FIX] <pro>Table: Fix autoHeight problem.
=> [FIX] <pro>Table: Fix autoHeight problem.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/DataSet.tsx, components-dataset/data-set/Record.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/table/ExpandedRow.tsx, components-pro/table/Profiler.tsx, components-pro/table/Table.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableEditor.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components-pro/table/VirtualRows.tsx, components-pro/table/VirtualWrapper.tsx, components-pro/table/demo/advanced-group.md, components-pro/table/demo/group.md, components-pro/table/demo/tree.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/table/style/index.less, components-pro/table/utils.tsx
[ADD] <pro>DataSet: Added strictPageSize property. 
[IMP] <pro>Table:  Optimize virtual scrolling and support tree-shaped virtual scrolling.
=> [ADD] <pro>DataSet: Added strictPageSize property. [IMP] <pro>Table: … 

components-pro/table/TableRow.tsx, components-pro/table/TableRowGroup.tsx, components-pro/table/TableStore.tsx, components-pro/table/VirtualWrapper.tsx, components-pro/table/style/index.less
[IMP] <pro>Table: Optimize virtual scrolling.
=> [IMP] <pro>Table: Optimize virtual scrolling.

components-pro/table/TableTBody.tsx, site/theme/template/Iframe/index.jsx, site/theme/template/Layout/index.jsx
[FIX] <pro>Table: Fix row draggable problem.
=> [FIX] <pro>Table: Fix row draggable problem.

components-pro/table/Table.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components-pro/table/customization-settings/CustomizationSettings.tsx, components-pro/table/style/index.less
[FIX] <pro>Table: Fix group display problem in virtual mode.
=> [FIX] <pro>Table: Fix group display problem in virtual mode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/Field.tsx, components-dataset/data-set/Record.tsx, components-dataset/stores/AttachmentStore.tsx
[IMP] <pro>Attachment: Optimize caching logic.
=> [IMP] <pro>Attachment: Optimize caching logic.

components-pro/table/TableEditor.tsx
[FIX] <pro>Table: Fix inline edit mode problem.
=> [FIX] <pro>Table: Fix inline edit mode problem.

components/notification/Notification.tsx
[FIX] Message: Fix onClose is not executed.
=> [FIX] Message: Fix onClose is not executed.

components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/ja_JP.tsx, components-pro/locale-context/locale.tsx, components-pro/locale-context/zh_CN.tsx, components-pro/table/query-bar/index.tsx, components/notification/Notification.tsx, components/notification/style/index.less
[FIX] Notification: Fix no animation of close all in foldCount mode.
=> [FIX] Notification: Fix no animation of close all in foldCount mode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/query-bar/index.tsx, components/popover/style/index.less, components/style/themes/default.less
[FIX] <pro>Table: Fix the sorting problem of query bar fields.
=> [FIX] <pro>Table: Fix the sorting problem of query bar fields.

components-pro/table/Column.tsx, components-pro/table/Table.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableEditor.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/VirtualRowMetaData.tsx, components-pro/table/customization-settings/CustomizationSettings.tsx, components-pro/table/customization-settings/column-groups/ItemTitle.tsx, components-pro/table/utils.tsx, components/bar-code/style/index.tsx, components/notification/Notice.tsx, components/popconfirm/index.tsx, components/use-config/index.tsx
[FIX] <pro>Table: Fix some problem of group and virtual.
=> [FIX] <pro>Table: Fix some problem of group and virtual.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/attachment/AttachmentList.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md, components-pro/table/ColumnGroups.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/customization-settings/CustomizationSettings.tsx, components-pro/table/demo/advanced-group.md, components-pro/table/demo/aggregation.md, package-lock.json
[ADD] <pro>Attachment: Added previewTarget property. 
[FIX] <pro>Table: Fix some problem of group and virtual mode.
=> [ADD] <pro>Attachment: Added previewTarget property. [FIX] <pro>Table… 

components-dataset/data-set/Group.tsx, components-dataset/data-set/Record.tsx, components-dataset/data-set/utils.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/table/Table.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableCol.tsx, components-pro/table/TableGroupCellInner.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components-pro/table/demo/advanced-group.md, components-pro/table/demo/basic.md, components-pro/table/demo/group.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md
[ADD] <pro>Table.Group: Added parentField property.
[FIX] <pro>Table.Column: Fix some problem of defaultWidth.
=> [ADD] <pro>Table.Group: Added parentField property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/field/FormField.tsx, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx
[FIX] <pro>DatePicker: Fix the problem of value setting in the range and multiple mode.
=> [FIX] <pro>DatePicker: Fix the problem of value setting in the range … 

components-pro/table/TableCell.tsx, components-pro/table/TableGroupCellInner.tsx, components-pro/table/demo/group.md
[FIX] <pro>Table: Fix some problem of group in virtual mode.
=> [FIX] <pro>Table: Fix some problem of group in virtual mode.

components-pro/table/Table.tsx, components-pro/table/TableRow.tsx, components-pro/table/TableTBody.tsx, components-pro/table/VirtualWrapper.tsx, components-pro/table/hooks.tsx, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/table/utils.tsx
[FIX] <pro>Table: Fix some problem of row dragging in tree mode.
=> [FIX] <pro>Table: Fix some problem of row dragging in tree mode.

components-pro/table/TableRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components-pro/table/VirtualRowMetaData.tsx, components-pro/table/VirtualWrapper.tsx, components-pro/table/demo/aggregation.md, components-pro/table/demo/virtual.md
[FIX] <pro>Table: Fix some problem of row type group in virtual mode.
=> [FIX] <pro>Table: Fix some problem of row type group in virtual mode.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/button/Button.tsx, components/button/Button.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md, components/tabs/Tabs.tsx, components/tabs/TabsWithContext.tsx
[ADD] configure: Added onTabsChange, onButtonClick properties.
=> [ADD] configure: Added onTabsChange, onButtonClick properties.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableStore.tsx
[FIX] <pro>Table: Fix the height calculation problem when there is a  horizontal scroll bar.
=> [FIX] <pro>Table: Fix the height calculation problem when there is a … 

components-pro/table/AggregationButton.tsx
[FIX] <pro>Table: Fix group aggregation limit button problem.
=> [FIX] <pro>Table: Fix group aggregation limit button problem.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/table/ErrorBar.tsx, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx
[IMP] <pro>Table: Opimize error bar.
[FIX] <pro>Table: Fix the problem of the lock of group set to false.
=> [IMP] <pro>Table: Opimize error bar.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/_util/UnitConvertor.tsx
[FIX] <pro>Select: Fix the problem that the drop-down box is not aligned when the browser font size is not default.
=> [FIX] <pro>Select: Fix the problem that the drop-down box is not alig… 

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/field/FormField.tsx, components-pro/form/Form.tsx, components-pro/lov/Lov.tsx, components-pro/table/Table.tsx, components-pro/table/TableFooterCell.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/TableHeaderRow.tsx, components-pro/table/TableStore.tsx, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
[ADD] configure: Added tableHeaderRowHeight, tableFooterRowHeight properties.
[ADD] <pro>Table: rowHeight supports hooks. 
[IMP] <pro>Attachment: The button displays a error color when the upload fails in popup mode.
=> [ADD] configure: Added tableHeaderRowHeight, tableFooterRowHeight pro… 

components/rc-components/table/BaseTable.jsx
=> [FIX] Table: Fix error.

components-dataset/data-set/DataSet.tsx
[FIX] <pro>DataSet: Fix commitData pageSize problem.
=> [FIX] <pro>DataSet: Fix commitData pageSize problem.

components/rc-components/trigger/PopupInner.jsx
[FIX] RcTrigger: Fix some problem.
=> [FIX] RcTrigger: Fix some problem.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/configure/index.tsx, components-dataset/data-set/DataSet.tsx, components-dataset/data-set/utils.tsx, components-pro/lov/LovView.tsx, components-pro/table/Table.tsx, components-pro/table/query-bar/TableDynamicFilterBar.tsx, components-pro/table/query-bar/index.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md, package.json
[ADD] configure: Add xlsx property.
=> [ADD] configure: Add xlsx property.

components/tabs/TabPane.tsx
[FIX] <pro>TabPane: Fixed count is not display by default.
=> [FIX] <pro>TabPane: Fixed count is not display by default.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/uploader/utils.tsx, components-pro/table/AggregationTree.tsx, components-pro/table/AggregationTreeGroups.tsx, components-pro/table/Column.tsx, components-pro/table/TableCell.tsx, components-pro/table/TableFooterCell.tsx, components-pro/table/TableHeaderCell.tsx, components-pro/table/demo/advanced-group.md, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md, components-pro/table/style/index.less, components-pro/table/utils.tsx
[ADD] <pro>Table.Column: Added aggregationTreeIndex property.
=> [ADD] <pro>Table.Column: Added aggregationTreeIndex property.

components-pro/field/style/index.less, components-pro/table/TableTBody.tsx
[FIX] <pro>Table: Fix row drag error in virtual mode.
[FIX] <pro>Form: Fix label align problem in grid layout.
=> [FIX] <pro>Table: Fix row drag error in virtual mode.

components-pro/field/style/mixin.less
[FIX] <pro>FormField: Fix multiple block style problem.
=> [FIX] <pro>FormField: Fix multiple block style problem.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/attachment/Attachment.tsx, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md
[ADD] <pro>Attachment: Added getUUID property.
=> [ADD] <pro>Attachment: Added getUUID property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableCell.tsx
[FIX] <pro>Table.Column: Fix onCell not working in virtual cells.
=> [FIX] <pro>Table.Column: Fix onCell not working in virtual cells.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/DataSet.tsx, components-dataset/data-set/enum.tsx, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md
[ADD] <pro>DataSet: Added selectAllPage, unSelectAllPage events.
=> [ADD] <pro>DataSet: Added selectAllPage, unSelectAllPage events.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/form/Form.tsx, components-pro/form/index.en-US.md, components-pro/form/index.zh-CN.md, components-pro/table/Table.tsx, components-pro/table/index.en-US.md, components-pro/table/index.zh-CN.md
[ADD] <pro>Table & Form: Added autoValidationLocate property.
=> [ADD] <pro>Table & Form: Added autoValidationLocate property.

components-dataset/data-set/Field.tsx, components-pro/cascader/Cascader.tsx, components/rc-components/cascader/Cascader.jsx
[FIX] <pro> Cascader: Fix error.
=> [FIX] <pro> Cascader: Fix error.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/form/Form.tsx, components-pro/table/TableStore.tsx, components-pro/table/demo/customized.md, components/collapse/CollapsePanel.tsx, components/collapse/demo/accordion.md, components/collapse/demo/borderless.md, components/collapse/demo/custom.md, components/collapse/demo/dataset.md, components/collapse/demo/mix.md, components/collapse/demo/noarrow.md, components/collapse/index.en-US.md, components/collapse/index.zh-CN.md, components/rc-components/collapse/Collapse.jsx, components/rc-components/collapse/Panel.jsx
[IMP] <pro>Table: The hideable of required columns is always false.
[ADD] Collapse.Panel: Added dataSet property.
=> [IMP] <pro>Table: The hideable of required columns is always false.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/button/Button.tsx, components-pro/button/style/index.less, components/button/Button.tsx, components/tabs/TabBar.tsx, components/tabs/style/index.less
[FIX] <pro>Button: Fix the problem of losing focus in loading state.
=> [FIX] <pro>Button: Fix the problem of losing focus in loading state.

components-pro/modal-container/ModalContainer.tsx
[FIX] Moda: Fix no mask problem.
=> [FIX] Moda: Fix no mask problem.

components-pro/table/TableStore.tsx
=> [FIX] <pro>Table: Fix error.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/button/style/index.less, components-pro/modal-container/ModalContainer.tsx, components/button/style/index.less
[FIX] <pro>Button: Fix loading style error.
[FIX] <pro>Modal: Fix the problem that the mask doesn't animate when closed.
=> [FIX] <pro>Button: Fix loading style error.

components/upload/UploadList.tsx, components/upload/style/index.less
[FIX] Upload: Fix error message is not display by Tooltip on item.
=> [FIX] Upload: Fix error message is not display by Tooltip on item.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/version/index.tsx, scripts/prepub.js
[FIX] version: Fix error in webpack5.
=> [FIX] version: Fix error in webpack5.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/form/demo/label-layout.md, components-pro/table/Table.tsx, components-pro/text-area/TextArea.tsx, components-pro/text-field/TextField.tsx, components/input/Input.tsx, components/input/TextArea.tsx, components/rc-components/select/Select.jsx
[FIX] <pro>Table: Fix loading state not clearing.
[IMP] Input & <pro>TextField: Optimize the display logic between floating label and placeholder to be consistent with material design.
=> [FIX] <pro>Table: Fix loading state not clearing.

components/tabs/style/index.less
[IMP] Tabs: Adjust validaiton badge style.
=> [IMP] Tabs: Adjust validaiton badge style.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/modal/demo/across-iframe.md, components/align/domAlign.tsx
[FIX] Popover: Fix the problem of not aligning inside iframe.
=> [FIX] Popover: Fix the problem of not aligning inside iframe.

CHANGELOG.zh-CN.md, components-pro/table/Table.tsx, components-pro/table/TableStore.tsx, components-pro/table/TableTBody.tsx, components-pro/table/utils.tsx
[FIX] <pro>Table: Fix the problem of virtual scrolling in maxHeight style.
=> [FIX] <pro>Table: Fix the problem of virtual scrolling in maxHeight style.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/tabs/Tabs.tsx, components/tabs/TabsWithContext.tsx, components/tabs/demo/flex.md, components/tabs/index.en-US.md, components/tabs/index.zh-CN.md, components/tabs/style/index.less
[ADD] Tabs: Added flex property.
=> [ADD] Tabs: Added flex property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/date-picker/DatePicker.tsx, components-pro/date-picker/DaysView.tsx, components-pro/date-picker/TimesView.tsx, components/configure/index.en-US.md, components/configure/index.tsx, components/configure/index.zh-CN.md
[ADD] configure: Added dateTimePickerOkButton property.
=> [ADD] configure: Added dateTimePickerOkButton property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/code-area/CodeArea.tsx, components-pro/code-area/enum.tsx, components-pro/lov/SelectionList.tsx, components-pro/lov/enum.tsx, components-pro/performance-table/Table.tsx, components-pro/performance-table/enum.tsx, components-pro/trigger-field/TriggerField.tsx, components-pro/trigger-field/enum.tsx, components/bar-code/enum.tsx, components/bar-code/index.tsx, components/cascader/enum.tsx, components/cascader/index.tsx, components/image-crop/enum.tsx, components/image-crop/index.tsx, components/table/enum.tsx, components/table/interface.tsx, components/tree/utils/dictUtil.ts
[IMP] Canonical enumeration type.
=> [IMP] Canonical enumeration type.

components/rc-components/collapse/Panel.jsx, components/tabs/TabPane.tsx
=> [FIX] Tabs: Fix ts error.

components/tabs/TabsWithContext.tsx
[FIX] Tabs: Fix infinite loop render by customization.
=> [FIX] Tabs: Fix infinite loop render by customization.

docs/react/big-number.en-US.md, docs/react/big-number.zh-CN.md
=> [UPD] update big number doc.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/Field.tsx, components-pro/attachment/Attachment.tsx, components-pro/attachment/Item.tsx, components-pro/attachment/demo/dataset.md, components-pro/attachment/index.en-US.md, components-pro/attachment/index.zh-CN.md, components-pro/attachment/style/index.less, components-pro/data-set/index.en-US.md, components-pro/data-set/index.zh-CN.md, components-pro/locale-context/en_GB.tsx, components-pro/locale-context/en_US.tsx, components-pro/locale-context/ja_JP.tsx, components-pro/locale-context/locale.tsx, components-pro/locale-context/zh_CN.tsx, package-lock.json
[ADD] <pro>Attachment: Added templateUrl property.
=> [ADD] <pro>Attachment: Added templateUrl property.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/table/TableHeaderCell.tsx, components-pro/tree-select/TreeNode.tsx, components-pro/tree-select/demo/basic.md, components-pro/tree/util.tsx, components/rc-components/tree/TreeNode.tsx
[FIX] <pro>TreeSelect.TreeNode: Fix selectable property not working.
[FIX] <pro>Table: Fix the problem that column width cannot be adjusted on mobile devices.
=> [FIX] <pro>TreeSelect.TreeNode: Fix selectable property not working.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/Record.tsx, components-pro/form/Form.tsx, components-pro/table/Table.tsx, components-pro/table/TableEditor.tsx, components-pro/table/demo/inline-edit.md, components/align/domAlign.tsx, components/table/FilterSelect.tsx, components/tabs/TabPane.tsx
[ADD] math: Added max, min methods.
[IMP] configure: attachment.getPreviewUrl return value supports hook types with return values of string and Promise<string>.
[FIX] <pro>Dropdown: Fix disabled attribute will affect child elements.
[FIX] formatter: Fix the problem of invalid formatting precision parameter for big numbers.
=> [ADD] math: Added max, min methods.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/data-set/DataSet.tsx, components-dataset/math/index.tsx, components-pro/pagination/Pagination.tsx, components/rc-components/table/Table.jsx, components/rc-components/table/ViewSection.jsx, components/table/demo/grouping-columns.md
[ADD] math: Added abs method.
[FIX] Table: Fix the problem that the combined column headers will bemisaligned.
=> [ADD] math: Added abs method.

components-dataset/math/index.tsx, components-pro/field/FormField.tsx, components-pro/field/utils.tsx, components-pro/number-field/NumberField.tsx, components-pro/table/TableCellInner.tsx, components-pro/table/query-bar/FilterSelect.tsx
[FIX] math: fix toString will show NaN.
[FIX] Fix the problem that value will be format as number in TextField.
=> [FIX] math: fix toString will show NaN.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/performance-table/customization-settings/column-groups/ItemSuffix.tsx, components-pro/table/TableFooterCell.tsx, components-pro/table/TableTBody.tsx, components-pro/table/TableVirtualRow.tsx, components-pro/table/customization-settings/column-groups/ItemSuffix.tsx, components/tabs/InvalidBadge.tsx, components/tabs/customization-settings/tab-groups/ItemSuffix.tsx
[FIX] Fix the bug of mobx-react in lower version.
=> [FIX] Fix the bug of mobx-react in lower version.

components/rc-components/input-number/index.jsx
[FIX] InputNumber: Fix the problem of not being able to enter decimals.
=> [FIX] InputNumber: Fix the problem of not being able to enter decimals.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/rc-components/table/BaseTable.jsx, components/rc-components/table/ColGroup.jsx, components/rc-components/table/HeadTable.jsx, components/rc-components/table/TableHeader.jsx, components/rc-components/table/TableHeaderRow.jsx
[FIX] Table: Fixed scrollbar issue in fixed header on mac.
=> [FIX] Table: Fixed scrollbar issue in fixed header on mac.

components/rc-components/input-number/index.jsx, docs/react/big-number.en-US.md, docs/react/big-number.zh-CN.md
[FIX] InputNumber: Fix BigNumber problem.
=> [FIX] InputNumber: Fix BigNumber problem.

components-pro/text-area/TextArea.tsx, components-pro/text-area/demo/autoSize.md
[FIX] <pro>TextArea: Fix exception called by autoSize when resized.
=> [FIX] <pro>TextArea: Fix exception called by autoSize when resized.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/performance-table/TableStore.tsx, components-pro/table/Table.tsx, docs/react/big-number.en-US.md, docs/react/big-number.zh-CN.md
[FIX] <pro>Table: Fix offsetParent error.
[FIX] <pro>PerformanceTable: Fix the display problem that the column width of personalized save may appear under large numbers.
=> [FIX] <pro>Table: Fix offsetParent error.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/icon-picker/IconCategory.tsx, components/rc-components/tree/List.tsx, components/tabs/TabBar.tsx
[FIX] Tabs: Fix scrollTo error in IE.
=> [FIX] Tabs: Fix scrollTo error in IE.

CHANGELOG.zh-CN.md, components/align/Align.tsx, components/trigger/Popup.tsx, components/trigger/PopupInner.tsx
[FIX] Trigger: Fix alignment problem.
=> [FIX] Trigger: Fix alignment problem.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/formatter/index.ts, components-pro/picture/PictureViewer.tsx, components-pro/picture/style/picture-viewer.less
& [FIX] <pro>DataSet: Fix the issue that the bigNumber formatting configuration was invalid.
=> [IMP] <pro>Picture: Optimize preview interface style and mouse wheel event interaction.

components-pro/check-box/style/mixin.less, components-pro/field/style/index.less, components-pro/modal/Modal.tsx
& [[FIX] <pro>CheckBox: Fix the issue of abnormal status style in the indeterminate of the CheckBox in the Form. & [FIX] <pro>Output: Fix the issue that the Output colon could not be aligned.
=> [FIX] <pro>Modal: Fix the abnormal flickering issue when closing Modal.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-pro/field/style/mixin.less, components-pro/table/query-bar/TableDynamicFilterBar.tsx, components-pro/table/query-bar/style/index.less, components-pro/text-field/style/mixin.less
Reverts open-hand/choerodon-ui#1405
=> Revert "[IMP] <pro>Table: Optimize dynamic filter bar style. & [FIX] <pro>Tex…"

components-pro/table/query-bar/TableDynamicFilterBar.tsx, components-pro/table/query-bar/style/index.less
Reverts open-hand/choerodon-ui#1438
=> Revert "[IMP] <pro>Table: Optimize dynamic filter bar style (February 1, 2023…"

components-pro/table/Table.tsx
…ribute disabled/readOnly can still be replicated.
=> [FIX] <pro>Table: Fixed the issue where the configuration dynamic attribute disabled/readOnly can still be replicated.

components/align/domAlign.tsx
…d window object contamination and resulted in an error.
=> [FIX] tooltip: Fixed the issue of determining whether an iframe caused window object contamination and resulted in an error.

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components-dataset/locale-context/LocaleContext.tsx, components-dataset/utils/index.ts, components-pro/core/ViewComponent.tsx, components-pro/field/FormField.tsx, components/locale-provider/index.tsx
Reverts open-hand/choerodon-ui#1916
=> Revert "[IMP] <pro>DatePicker: Improved 12-hour time display in Chinese envir…"
